### ISSUE TITLE
App not working without geoposition determining hardware

### ISSUE THREAD

**Issue by gray-hacker** [danrabbit/nimbus#103] opened 2020-07-14 07:27 UTC
Custom Location Can't be set. App not working without hardware determinig geoposition, which is not included in my laptop.

**Comment by gray-hacker** [comment] 2020-07-14 07:29
App not working without hardware determinig geoposition, whic is not included in my laptop.

**Comment by danrabbit** [comment] 2020-07-14 15:51
Closing as a duplicate of #96

**Closed by danrabbit** 2020-07-14 15:51 UTC
