### ISSUE TITLE
Unable to find location

### ISSUE THREAD

**Issue by MarilouHaines** [danrabbit/nimbus#101] opened 2020-03-24 06:31 UTC
It would be nice to be able to enter your location. Not everyone lives in a metropolitan area.
![Screenshot from 2020-03-24 01 28 15](https://user-images.githubusercontent.com/57438342/77395226-189d9780-6d6f-11ea-954e-1125fdea2509.png)

**Comment by danrabbit** [comment] 2020-06-17 18:03
Closing as a duplicate of #31

**Closed by danrabbit** 2020-06-17 18:03 UTC
