### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by ernmander** [danrabbit/nimbus#76] opened 2018-05-16 08:58 UTC
Would it be possible to have the ability to manually set a location for the weather? I've noticed when using the app in my office it auto detects my broadband providers location, which is nowhere near the actual location I am sat.

**Comment by cassidyjames** [comment] 2018-08-03 19:23
I know Nimbus uses the system's location services to determine the location, so I don't know if this is within the scope of the app. If it's wrong for this app, it's wrong for any app on the OS that uses the OS APIs.

**Comment by skewty** [comment] 2018-09-21 02:47
See #31

**Comment by dracid** [comment] 2018-10-18 20:06
Hello! Any updates?
It's super annoying that I paid $1 for the app to support the developer, but there isn't the most RUDIMENTARY way to even specify the location, and people have been asking for implementation for more than a year.

**Comment by cassidyjames** [comment] 2018-10-19 00:33
This is a duplicate of #31. The feature is on the wishlist.

**Comment by IKUWILL** [comment] 2018-11-16 15:08
Location shown on my machine is 400+ miles from the actual location. Want to say this as nicely as possible, but because I love the OS I need to say. If an app really doesn't work, it should not be put on the app center, because it hurts the brand, and turns off newcomers. I am sure it is probably not a simple fix. But it is what it is, if an app has one function that does not work, it really needs fixed, primarily not for technical reasons, but for the image perceived by the users.

**Comment by cassidyjames** [comment] 2018-11-16 17:20
@IKUWILL and the app does work, likely for the majority of the hundreds of people who are downloading it. Further, if the issue is not in the app itself but in some specific situation occurring in the low-level location services library, then there's even less that the app developer can do to fix it. 

Reporting your issue along with as much diagnostic information as possible to [GeoClue](https://gitlab.freedesktop.org/geoclue/geoclue) would be the best route to getting it fixed for you and others who may be experiencing this issue not only in Nimbus, but in other apps that use GeoClue location services. https://gitlab.freedesktop.org/geoclue/geoclue

**Comment by janxkoci** [comment] 2019-06-10 14:45
Hi, I would like to add a few points to this issue:

First of all - the app doesn't ask for permission to use my location and doesn't show up in the Privacy settings.

Second, the apps that *do* show up there, such as GNOME Maps, also *do* show my correct location with the precision of a few meters. Definitely not a city 300 km away. So the claim

> If it's wrong for this app, it's wrong for any app on the OS that uses the OS APIs.

is just wrong, unless I completely misunderstand what you mean by OS APIs.

**Comment by JuanSpecht** [comment] 2019-07-24 21:39
Same here, Gnome maps shows my location just a few blocks from my house while Nimbus is getting it wrong by more than 400 Km, even though I gave it permission to use location services and it appears in the corresponding switchboard plug.
It is a shame, because I love the minimalist approach of this app :/

**Comment by cassidyjames** [comment] 2019-07-25 04:33
It looks like GNOME Maps requests your device's _exact_ physical location, which makes sense since it's a mapping app. However, a weather app should request the city-level location since weather data is provided at a city level, and privacy-wise it doesn't need your exact location.

It looks like GNOME Weather also uses city-level location. Are you seeing similar issues there?

**Comment by JuanSpecht** [comment] 2019-07-25 04:48
You are right! Thanks for your time.
I checked GNOME Weather and it shows the same location as Nimbus. However, an error of 400 Km is still too much for a weather app (two weather apps now :P)

**Comment by cassidyjames** [comment] 2019-07-25 05:32
@JuanSpecht that at least narrows it down! For some reason, the city-level location that GeoClue is reporting is far less accurate than you'd expect. @danrabbit would it be reasonable to have a setting somehow in Nimbus to opt into precise location for these instances?

**Comment by janxkoci** [comment] 2019-07-25 09:08
I think the right thing to do is to show correct location by default.

**Comment by Justinzobel** [comment] 2019-09-22 12:10
@cassidyjames reporting to geoclue doesn't often help as the IP address I route through is in an entirely different state due to the way my ISP does traffic. A manual way to enter the location is needed in this instance and many others that use the same tools to look up a user's location.

Also with elementary often focussing on privacy, it'd be nice for an application not to REQUIRE a users location in order to function.

**Comment by saidbakr** [comment] 2019-12-07 08:04
It is incorrect or limited implementation of [HIG](https://elementary.io/docs/human-interface-guidelines#accessible-configuration) regarding **Ask the Operating System** because we did not deal with mobile phones the majority of them is supplied with GPS sensors, but we deal with desktops PCs. The application need either its own settings management that allows enter location manually or the OS need that setting to be available globally.

In this case, I think, the first choice is more reliable.

**Comment by janxkoci** [comment] 2019-12-07 13:39
@saidbakr I think the second option is better - let the application ask for location and let the system give location the way user finds fit, be it automatic or manual.

**Comment by saidbakr** [comment] 2019-12-07 22:44
> @saidbakr I think the second option is better - let the application ask for location and let the system give location the way user finds fit, be it automatic or manual. This way it's way more modular.

However, the second option will require modification on the OS either in its basic settings or using some third party apps such as elementary-tweaks!

**Comment by janxkoci** [comment] 2019-12-08 14:19
Which will benefit everyone, not just a single app. Also it's just improvements to the existing system, it's not like that hasn't been done before.

**Comment by danrabbit** [comment] 2020-06-17 18:03
Closing as a duplicate of #31

**Closed by danrabbit** 2020-06-17 18:03 UTC
