### ISSUE TITLE
Error 403 - Unable to get weather data

### ISSUE THREAD

**Issue by jrizzoli** [danrabbit/nimbus#72] opened 2018-03-26 17:16 UTC
Installed on: eOS 0.4
Installed from: appCenter
Dependencies: geoclue-2.0 is installed
Repro steps: Open nibus > City is correctly located > No weather data (sun + "--" as temperature).
Logs: 
```
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
(com.github.danrabbit.nimbus:7188): GWeather-WARNING **: Failed to get IWIN forecast data: 403 Forbidden
```

**Comment by danrabbit** [comment] 2020-06-17 18:04
Closing as a duplicate of #30

**Closed by danrabbit** 2020-06-17 18:04 UTC
